export const PROJECTS = [
  {
    preview: "",
    repo: "https://github.com/CheoR/shipItOut-client",
    link: "https://shipitout.herokuapp.com/",
    aria: "GitHub Project: Ship It Out",
    label: "ShipItOut",
    description: "In sit amet libero eros.",
    tags: ["Django", "Heroku", "Node", "MUI", "React"],
  },
  {
    preview: "",
    repo: "https://github.com/CheoR/pack-it-up",
    link: "https://cr-demo--packitup.netlify.app/",
    aria: "GitHub Project: Pack It Up",
    label: "PackItUp",
    description: "In sit amet libero eros.",
    tags: ["React"],
  },
  {
    preview: "",
    repo: "https://github.com/CheoR/BeerMe",
    link: "",
    aria: "GitHub Project: Beer Me",
    label: "BeerMe",
    description: "Praesent posuere viverra tempor. ",
    tags: ["Enzyme", "Formik", "React", "Yup"],
  },
  {
    preview: "",
    repo: "https://github.com/CheoR/recommend_wine",
    link: "",
    aria: "GitHub Project: Wine Recommender",
    label: "Wine Recommender",
    description: "Nunc vitae velit consequat massa ullamcorper sodales. ",
    tags: ["CI", "Django", "TDD"],
  },
  {
    preview: "",
    repo: "https://github.com/CheoR/FreeCodeCampProjects",
    link: "",
    aria: "GitHub Project: Free Code Camp Projects",
    label: "FCC Projects",
    description:
      "Phasellus vitae ante tortor. Sed dapibus dui id libero dapibus ornare.",
    tags: ["CSS", "HTML", "JavaScript"],
  },
  {
    preview: "",
    repo: "https://codepen.io/CheoR/full/QzPJbQ",
    link: "",
    aria: "GitHub Project: Code Pen Projects",
    label: "CodePen",
    description:
      "Aliquam erat volutpat. Morbi bibendum sem id dolor euismod interdum.",
    tags: ["CSS", "HTML", "JavaScript"],
  },
  {
    preview: "",
    repo: "https://github.com/CheoR/portfolio",
    link: "https://cheor.github.io/portfolio/",
    aria: "Personal Portfolio",
    label: "Personal Portfolio",
    description: "Quisque ultricies aliquam gravida.",
    tags: ["CSS", "Gatsby", "HTML", "JavaScript"],
  },
  {
    preview: "",
    repo: "",
    link: "./assets/pdf/Cheo_Roman_Resume.pdf",
    aria: "Downloadable Resume",
    label: "Resume",
    description: "Lorem, ipsum dolor sit amet consectetur.",
    tags: ["Resume"],
  },
];
